# Probe 16b - follow-ups. STRICTLY READ-ONLY against non-sandbox projects.
#
#   1. Persist the pseudonym -> real name mapping to Secrets/ (git-ignored) so the BFF can be
#      pointed at a populated read-only project without the name ever entering git history.
#   2. Characterize the HTTP 500 that the largest project returns for `test-sets` while every
#      other collection on the same project reads fine. P1's grid has to survive this, so the
#      shape of the failure matters: whole-collection, or one poisoned row?
#   3. Confirm the corrected tree-root rule (probe 15) holds on a project that actually has trees.
#      Probe 15 verified it against a near-empty project; that is exactly the kind of subset
#      generalization probe 15 itself was about.
$ErrorActionPreference = 'Stop'

$repoRoot = Split-Path -Parent (Split-Path -Parent $PSScriptRoot)
$c = Get-Content (Join-Path $repoRoot 'Secrets\ALM_API_credentials.json') -Raw | ConvertFrom-Json
$base = ([string]$c.alm_adress).Trim().TrimEnd('/')
if ($base -notmatch '/qcbin$') { $base = "$base/qcbin" }

$script:maskTerms = [System.Collections.Generic.List[string]]::new()
foreach ($m in @(([Uri]$base).Host, $c.api_key, $c.api_secret, $c.domain, $c.project)) {
    if ($m) { $script:maskTerms.Add([string]$m) }
}
function Mask([string]$s) {
    if (-not $s) { return $s }
    foreach ($m in $script:maskTerms) { $s = $s -replace [regex]::Escape($m), 'REDACTED' }
    return $s
}
function Say([string]$s) { Write-Host (Mask $s) }

$iwr = @{ TimeoutSec = 60; SkipHttpErrorCheck = $true; MaximumRedirection = 0; AllowInsecureRedirect = $true }

$body = @{ clientId = $c.api_key; secret = $c.api_secret } | ConvertTo-Json -Compress
$null = Invoke-WebRequest @iwr -Uri "$base/rest/oauth2/login" -Method Post `
    -ContentType 'application/json' -Body $body -SessionVariable session
$xsrf = ($session.Cookies.GetCookies([Uri]$base) | Where-Object Name -eq 'XSRF-TOKEN').Value
$null = Invoke-WebRequest @iwr -Uri "$base/rest/site-session" -Method Post `
    -Headers @{ 'X-XSRF-TOKEN' = $xsrf } -WebSession $session
$r = Invoke-WebRequest @iwr -Uri "$base/v2/rest/is-authenticated" `
    -Headers @{ Accept = 'application/json' } -WebSession $session
if ($r.StatusCode -eq 200) {
    $me = ($r.Content | ConvertFrom-Json).AuthenticationInfo.Username
    if ($me) { $script:maskTerms.Add([string]$me) }
}
Say 'signed in'

function Get-Only([string]$Uri) {
    return Invoke-WebRequest @iwr -Uri $Uri -Method Get `
        -Headers @{ Accept = 'application/json' } -WebSession $session
}

try {
    # --- rebuild the ranking, same GET-only counting as probe 16 -------------------------------
    $dn = $c.domain
    $pr = Get-Only "$base/rest/domains/$dn/projects"
    $pj = $pr.Content | ConvertFrom-Json
    $projNames = @()
    foreach ($p in @($pj.Projects.Project)) { if ($p.Name) { $projNames += [string]$p.Name } }
    if (-not $projNames) { foreach ($p in @($pj.Project)) { if ($p.Name) { $projNames += [string]$p.Name } } }

    $ranked = [System.Collections.Generic.List[hashtable]]::new()
    $i = 0
    foreach ($pn in $projNames) {
        $proj = "$base/rest/domains/$dn/projects/$pn"
        $total = 0
        foreach ($col in @('requirements', 'tests', 'defects', 'test-instances', 'runs')) {
            $cr = Get-Only "$proj/$col`?fields=id&page-size=1"
            if ($cr.StatusCode -eq 200) {
                try { $total += [int](($cr.Content | ConvertFrom-Json).TotalResults) } catch {}
            }
        }
        $isOurs = ($pn -eq $c.project)
        if (-not $isOurs) { $i++ }
        $ranked.Add(@{ name = $pn; total = $total; ours = $isOurs
            alias = $(if ($isOurs) { 'SANDBOX' } else { "PROJECT-$i" })
        })
    }

    # --- 1. persist the mapping into git-ignored Secrets/ --------------------------------------
    $mapPath = Join-Path $repoRoot 'Secrets\alm-read-projects.json'
    $payload = [ordered]@{
        note    = 'Generated by scripts/probe/probe-projects-2.ps1. READ-ONLY targets for P1 validation. Git-ignored on purpose - these are other teams project names. Never copy a value from this file into a doc, fixture or commit.'
        domain  = $dn
        sandbox = $c.project
        projects = @(
            foreach ($p in ($ranked | Sort-Object { $_.total } -Descending)) {
                [ordered]@{ alias = $p.alias; name = $p.name; totalRows = $p.total
                    access = $(if ($p.ours) { 'read-write (designated sandbox)' } else { 'READ-ONLY' })
                }
            })
    }
    $payload | ConvertTo-Json -Depth 5 | Set-Content -Path $mapPath -Encoding utf8
    Say ("wrote pseudonym -> real-name map to Secrets\alm-read-projects.json ({0} projects)" -f $ranked.Count)
    Say '  (Secrets/ is git-ignored; the real names never enter the repo)'

    $biggest = ($ranked | Where-Object { -not $_.ours } | Sort-Object { $_.total } -Descending | Select-Object -First 1)
    Say ("largest read-only project = {0} ({1} rows)" -f $biggest.alias, $biggest.total)
    $bigProj = "$base/rest/domains/$dn/projects/$($biggest.name)"

    # --- 2. characterize the test-sets 500 -----------------------------------------------------
    Say ''
    Say '=== test-sets HTTP 500: whole collection, or a poisoned row? ==='

    foreach ($q in @('?fields=id&page-size=1', '?fields=id&page-size=1&start-index=1',
            '?page-size=1', '?fields=id,name&page-size=1', '?fields=id&page-size=2000')) {
        $rr = Get-Only "$bigProj/test-sets$q"
        $snippet = ''
        if ($rr.StatusCode -ne 200) {
            $snippet = (([string]$rr.Content) -replace '\s+', ' ')
            if ($snippet.Length -gt 260) { $snippet = $snippet.Substring(0, 260) }
        } else {
            try { $snippet = "TotalResults=" + (($rr.Content | ConvertFrom-Json).TotalResults) } catch {}
        }
        Say ('test-sets{0,-40} -> HTTP {1}  {2}' -f $q, $rr.StatusCode, $snippet)
    }

    # Does the parent tree read? If folders are fine but the leaf collection 500s, the fault is
    # in the test-set rows, not in the module.
    foreach ($col in @('test-set-folders', 'test-instances', 'runs')) {
        $rr = Get-Only "$bigProj/$col`?fields=id&page-size=1"
        $extra = ''
        if ($rr.StatusCode -eq 200) { try { $extra = "TotalResults=" + (($rr.Content | ConvertFrom-Json).TotalResults) } catch {} }
        Say ('{0,-20} -> HTTP {1}  {2}' -f $col, $rr.StatusCode, $extra)
    }

    # Is it project-specific, or does this collection 500 elsewhere too?
    Say ''
    Say '--- test-sets across all readable projects ---'
    foreach ($p in ($ranked | Sort-Object { $_.total } -Descending)) {
        $rr = Get-Only "$base/rest/domains/$dn/projects/$($p.name)/test-sets?fields=id&page-size=1"
        $extra = ''
        if ($rr.StatusCode -eq 200) { try { $extra = "TotalResults=" + (($rr.Content | ConvertFrom-Json).TotalResults) } catch {} }
        Say ('  {0,-12} -> HTTP {1}  {2}' -f $p.alias, $rr.StatusCode, $extra)
    }

    # --- 3. re-verify the corrected tree-root rule on a project with real trees ----------------
    Say ''
    Say '=== tree-root rule re-check on a POPULATED project ==='
    foreach ($t in @('requirements', 'test-folders', 'test-set-folders', 'release-folders',
            'bpm-folders', 'resource-folders')) {
        $line = "{0,-18}" -f $t
        foreach ($pv in @('-1', '0')) {
            $rr = Get-Only "$bigProj/$t`?query={parent-id[$pv]}&fields=id,name&page-size=5"
            if ($rr.StatusCode -ne 200) { $line += ("  parent={0}:HTTP{1}" -f $pv, $rr.StatusCode); continue }
            $j = $rr.Content | ConvertFrom-Json
            # COUNT ONLY - names in a foreign project are that team's data, not ours to print.
            $line += ("  parent={0}:{1} row(s)" -f $pv, $j.TotalResults)
        }
        Say $line
    }
    Say '(row counts only - foreign project node names are deliberately not printed)'
} finally {
    if ($xsrf) {
        $null = Invoke-WebRequest @iwr -Uri "$base/rest/site-session" -Method Delete `
            -Headers @{ 'X-XSRF-TOKEN' = $xsrf } -WebSession $session
        $null = Invoke-WebRequest @iwr -Uri "$base/authentication-point/logout" -Method Post `
            -Headers @{ 'X-XSRF-TOKEN' = $xsrf } -WebSession $session
        Say ''
        Say 'session torn down'
    }
}
